title: 智能感知与控制课题组（Smart Perception and Control Lab）
name: 智能感知与控制课题组（Smart Perception and Control Lab）
url: https://xj-group.github.io

exclude: [bibble, README.md, Makefile, screenshot.png]

# 代码高亮模块
highlighter: pygments

# 博客/news 新闻文章路径格式
permalink: /blog/:year/:month/:day/:title.html

# 团队成员分组，顺序和显示名
roles:
  - key: faculty
    name: 教师
  - key: postdoc
    name: 博士后
  - key: grad
    name: 硕士研究生
  - key: ugrad
    name: 本科生
  - key: collab
    name: 合作单位
  - key: alum
    name: 校友

# 首页显示新闻条数
front_page_news: 6

# 基础路径（一般留空）
base: ''

# 项目 collection 配置
collections:
  projects:
    output: true

# 导航栏链接与命名
navigation:
  - title: 主页
    link: /
  - title: 团队成员
    link: /people.html
  - title: 课题与项目
    link: /research.html
  - title: 科研成果
    link: /publications.html
  - title: 联系我们
    link: /contact.html

# 网站描述和邮箱
description: 专注于人工智能、自动化与多智能体系统的理论及应用研究
email: 615xujia@tongji.edu.cn
